[package]
name = "gwsim-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
gwsim-data = { path = "../gwsim-data" }
rand_chacha.workspace = true
rand_core.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
proptest.workspace = true
insta.workspace = true
ron.workspace = true

[lints]
workspace = true
