[package]
name = "gwsim-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
gwsim-opt = { path = "../gwsim-opt" }
gwsim-engine = { path = "../gwsim-engine" }
gwsim-data = { path = "../gwsim-data" }
clap.workspace = true
serde_json.workspace = true
rayon.workspace = true
ron.workspace = true

[build-dependencies]
gwsim-data = { path = "../gwsim-data" }

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
gwsim-data = { path = "../gwsim-data" }

[[bin]]
name = "gwsim"
path = "src/main.rs"

[lints]
workspace = true
